version: "3"

services:
  db:
    image: mariadb:10.5
    ports:
      - "3306:3306"
    volumes:
      - db_vol:/var/lib/mysql
    env_file: ./conf/mariadb/.env
    container_name: mariadb
    environment:
      TZ: Asia/Seoul
    restart: always

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    container_name: redis
    restart: always

  spring:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    links:
      - db
      - redis
    env_file: ./conf/spring/.env
    restart: always

networks:
  backend:

volumes:
  db_vol: