server:
  address: ${SPRING_SERVER_HOST}
  port: ${SPRING_SERVER_PORT}

spring:
  config:
    use-legacy-processing: true

  profiles:
    active: local
    default: local
    include:
      - 'system'
      - 'jwt-config'

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}

  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect

cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    region:
      static: "ap-northeast-2"
    stack:
      auto: false
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
