jwt:
  secret: "please set this property"
  accessTokenExpTime: 600000
  refreshTokenExpTime: 604800016

server:
  address: ${SPRING_SERVER_HOST}
  port: ${SPRING_SERVER_PORT}
  protocol: "http"

spring:
  devtools:
    add-properties: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 50MB
      location: /uploads

  # SQL 로그 보여지게 설정
  level:
    org.hibernate.sql: DEBUG
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
        type:
          descriptor:
            sql:
              BasicBinder: trace
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# SpringDoc (Swagger 3.0 ) Config
springdoc:
  swagger-ui:
    path: '/swagger-ui.html'
    groups-order: desc
    operations-sorter: method
    disable-swagger-default-url: true
  api-docs:
    path: '/api-docs'
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# Custom Variables
custom:
  twilio:
    sid: ${TWILIO_SID}
    token: ${TWILIO_TOKEN}
    phone-number: ${TWILIO_PHONE_NUMBER}
  path:
    upload-images: ${FILE_UPLOAD_DIR}
