version: "3"

services:
  mariadb_local:
    image: mariadb:10.5
    ports:
      - "3307:3306"
    env_file: "../prod/.prod.mariadb.env"
    container_name: mariadb_local
    environment:
      TZ: Asia/Seoul
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - db_vol:/var/lib/mysql

  redis_local:
    image: redis:7.0
    ports:
      - "6380:6379"
    container_name: redis_local
    restart: unless-stopped
    environment:
      TZ: Asia/Seoul
    networks:
      - backend

  spring_local:
    build: "../../"
    depends_on:
      - mariadb_local
      - redis_local
    links:
      - mariadb_local
      - redis_local
    ports:
      - "8888:8080"
    env_file: ".local.spring.env"
    restart: unless-stopped
    container_name: spring_local
    networks:
      - backend

  nginx:
    image: "nginx:stable"
    container_name: nginx_local
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80/tcp"
    links:
      - spring_local
    depends_on:
      - spring_local
    networks:
      - default
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_vol:
