version: "3"

services:
  spring_prod:
    build: "../../"
    ports:
      - "8081"
    env_file: ".prod.spring.env"
    restart: unless-stopped
    container_name: spring_prod
    networks:
      - default

  nginx:
    image: "nginx:stable"
    container_name: nginx_prod
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80/tcp"
    links:
      - spring_prod
    depends_on:
      - spring_prod
    networks:
      - default

networks:
  default:
    external: true
    name: frolic
