version: "3"

services:
  spring_prod:
    container_name: spring_prod
    build: "../../"
    ports:
      - "8080:8080"
    env_file: ".prod.spring.env"
    restart: always
    depends_on:
      - mariadb_prod

  webserver:
    container_name: nginx
    image: "nginx:latest"
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    links:
      - spring_prod
    depends_on:
      - spring_prod

  mariadb_prod:
    image: "mariadb:10.5"
    volumes:
      - /home/ec2-user/backup/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .prod.mariadb.env

  redis_prod:
    container_name: redis_prod
    restart: always
    image: "redis:6.2"
    ports:
      - "6379:6379"
