version: "3"

services:
  spring_prod:
    build: "../../"
    ports:
      - "8081"
    env_file: ".prod.spring.env"
    restart: unless-stopped
    container_name: spring
    depends_on:
      - mariadb_prod

  nginx:
    image: "nginx:stable"
    container_name: nginx_prod
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80/tcp"
    links:
      - spring_prod
    depends_on:
      - spring_prod

  mariadb_prod:
    image: "mariadb:10.5"
    container_name: mariadb
    volumes:
      - ./home/ec2-user/backup/mysql:/var/lib/mysql
    ports:
      - "3306:3306/tcp"
    env_file:
      - .prod.mariadb.env

  redis_prod:
    image: "redis:6.2"
    container_name: redis
    ports:
      - "6379:6379/tcp"
